### ISSUE TITLE
Explicit option to download / export the canvas as an image or PDF

### ISSUE THREAD

**Issue by newcastle-living-lab** [newcastle-living-lab/living-lab#18]
**Is your feature request related to a problem? Please describe.**
The canvas does not have an explicit option to export as a PDF or image.

**Describe the solution you'd like**
To have a download/export button which exports the canvas as an image or PDF.

**Additional context**
At present, whilst it is possible to save the canvas as an image, it is not immediately apparent to the End User.

**Comment by craigrodway** [comment]
A 'Download' option has been added to the header menu in 1.26.0-beta.3.

**Comment by craigrodway** [comment]
Completed in 1.26.0.
